# 03 넘파이
---
* Numpy(Numerical Python) : 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
* 루프를 사용하지 않고 빠른 배열 연산 속도를 보장
* 넘파이 기본 지식과 자주 사용되는 넘파이 API에 관해 설명

### Numpy ndarray 개요
* 넘파이 기반 데이터 타입 : ndarray로, 다차원 배열을 쉽게 생성, 다양한 연산 수행 가능
* __array() 함수__ : 리스트 같은 다양한 인자를 받아 ndarray로 변환하는 기능
* ndarray.shape : ndarray의 크기(행, 열)를 튜플 형태로 갖고있음
* ndarray.ndim : array의 차원 확인
* array1과 3은 동일한 데이터 값을 갖고 있지만, 리스트 [ ]는 1차원을, 리스트의 리스트 [[ ]]는 2차원 형태로 표현됨

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입
* ndarray 내 입력 가능한 데이터 형태
    1. 숫자 : int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), complex 타입 등
    2. 문자열
    3. 불
    
* 같은 데이터 타입만 연산 가능 한 객체에 int, float이 함께 있을 수 없음 (리스트와 다른점)
* ndarray.dtype : ndarray 내의 데이터 타입 확인

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


* 만약 다른 유형이 섞여 있는 리스트를 ndarray로 변형한다면?
* 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용
* case 1: int 값이 str으로 변경, 데이터타입이 유니코드 문자열 로 변환
* case 2: float 64 형으로 변환

In [5]:
# case 1 : int + str
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# case 2 : int + float
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


* astype() 메서드 : ndarray내 데이터값의 타입 변경
* int32 -> float64 -> int32 (소수점 이하 버림, 반올림 x)

In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones
* 특정 크기와 차원을 가진 ndarray를 연속값, 0 또는 1로 초기화하여 생성하는 방법
* arange() : array를 range()로 표현
* zeros() : 모든 값을 0으로 채운 특정 shape을 가진 ndarray를 반환
* ones() : 모든 값을 1으로 채운 특정 shape을 가진 ndarray를 반환
* zeros()와 ones()는 dtype 지정 안하면 default로 float64형의 데이터로 채움

In [7]:
# 0 ~ 9 까지 int로 이뤄진 1차원 ndarray 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
# (3,2) shape
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape : ndarray의 차원과 크기 변경

In [9]:
# 1차원 ndarray 생성
array1 = np.arange(10)
print('array1:\n', array1)

# 2,5 shape으로 변경
array2 = array1.reshape(2,5)
print('array2:\n',array2)

# 5, 2 shape으로 변경
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# 변경 불가
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
# -1 사용하면 호환되는 shape으로 알아서 변경
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
# -1 사용해도 변경 불가한 경우
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

* tolist() 메서드 : 리스트 자료형으로 변경

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### Indexing : ndarray의 데이터 세트 선택하기
1. 특정 데이터 추출 : 원하는 위치의 인덱스값 지정
2. 슬라이싱 : ':' 사용하여 범위 지정
3. Fancy indexing : 일정 인덱싱 집합을 리스트 혹은 ndarray형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
4. Boolean indexing : 특정 조건에 해당 여부인 True/False 값 집합을 기반으로, True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환

__단일값 추출 : [인덱스값]__

In [14]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [15]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
# 단일 인덱스를 이용해 특정 위치의 값 수정
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
# 2차원 ndarray 단일값 추출[행 인덱스번호 : 열 인덱스 번호]
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* 다차원 ndarray는 축(axis) 구분을 가져서 축에 따른 연산을 지원함.
* 축 기반 연산에서 axis 생략시 defualt는 axis0
* 2차원 : axis0, axis1 = 행, 열
* 3차원 : axis0, axis1, axis2 = 행, 열, 높이

__Slicing__

In [18]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

# 시작, 종료 인덱스 생략 가능
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])

# 행 혹은 열 축 한쪽에만 슬라이싱 적용하고, 다른 축에는 단일 인덱스 적용해도 됨
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


* 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
* 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환

In [21]:
# axis0축의 첫 번째 행 반환. 1차원
print(array2d[0])

# axis0 축의 두 번째 행 반환. 1차원
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


__fancy indexing__
* 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [22]:
# 2차원 ndarray 생성
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d =>', array2d)

# tolist() 해서 list 형태로 ',' 반환
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d => [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


__Boolean indexing__
* 조건 필터링과 검색을 동시에 할 수 있음
* for loop/ if else 보다 간단하게 구현 가능
* [조건문입력]
* 불린 인덱싱 동작 단계
    1. Step 1. ndarray의 필터링 조건을 [ ]에 기재
    2. Step 2. False 값 무시, True에 해당하는 __인덱스값만 저장__ True 자체인 1을 저장하는게 아님
    3. Step 3. 저장된 인덱스 데이터셋으로 ndarray 조회

In [23]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [24]:
# ndarray에 조건 할당하면 값이 어떻게 변하는지 확인
# True값이 있는 위치만 값으로 자동 변환해 출력해주는 원리
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [25]:
# 위와 동일한 boolean형태의 ndarray를 만들고
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])

# array1d[]내에 입력하면 동일 한 결과과 반환됨
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
# 직접 인덱스 집합을 만들어 대입한것과 동일
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 넘파이에서 행렬을 정렬하는 대표적인 방법 : np.sort(), ndarray.sort()
* 정렬된 행렬의 인덱스 반환 방법 : argsort()

__행렬 정렬 np.sort(), ndarray.sort()__
* np.sort() : 기존 행렬은 유지한 채 정렬된 행렬을 반환
* ndarray.sort() : 행렬 자체를 정렬한 형태로 변환, 함수 호출 후 기존 행렬 반환값은 None
* default가 오름차순임

In [27]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


* 내림차순으로 정렬하려면 [::-1] 적용

In [28]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


* 행렬이 2차원 이상일 경우 : axis 축 값 설정을 통해 행 또는 열 방향으로 정렬 수행 가능
* axis=0인 경우 위에있는 행이 아래있는 행의 원소보다 낮은 값
* axis=1인 경우 왼쪽에 있는 열이 오른쪽에 있는 열의 원소보다 낮은 값

In [29]:
# 2차원 행렬 생성
array2d = np.array([[8, 12], 
                   [7, 1 ]])

array2d_2 = np.array([[8, 12], 
                   [7, 15 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_2_axis0 = np.sort(array2d_2, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_2_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

sort_array2d_2_axis1 = np.sort(array2d_2, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_2_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
로우 방향으로 정렬:
 [[ 7 12]
 [ 8 15]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 7 15]]


* axis 설정 안한경우 : axis=1이 default

In [30]:
# 2차원 행렬 생성
array2d = np.array([[8, 12], 
                   [7, 1 ]])

array2d_2 = np.array([[8, 12], 
                   [15, 7 ]])

sort_array2d = np.sort(array2d)
print('축 설정 없이 정렬:\n', sort_array2d)

sort_array2d_2= np.sort(array2d_2)
print('축 설정 없이 정렬:\n', sort_array2d_2)


축 설정 없이 정렬:
 [[ 8 12]
 [ 1  7]]
축 설정 없이 정렬:
 [[ 8 12]
 [ 7 15]]


__정렬된 행렬의 인덱스 반환__

In [31]:
# 1차원 ndarray 생성
org_array = np.array([ 3, 1, 9, 5]) 

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

__행렬 내적(행렬곱) : np.dot( )__

In [34]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


__전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬__

In [35]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


Breaktime -- 5min